### ISSUE TITLE
Boss spec does not work for defeat task

### ISSUE THREAD

**Issue by Mike5357** [Eufranio/PBQ-PixelmonExpansion#3]
The 'boss' spec does not work for pbq:defeat_wild_poke. 
With mode set to EXACT and boss spec set to any of the following (as would normally work via pokespawn), any pokemon seems to count towards the goal as opposed to just bosses.
- pokemonSpec="Boss:1"
- pokemonSpec="b:1"
- pokemonSpec="b:Uncommon"

Other specs such as the 'form' spec (using f:1 etc) seem to work fine, the issue seems to solely be with the 'boss' spec.

**Comment by Eufranio** [comment]
Fixed in 2.4.
